name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: my-vite-app/package-lock.json  # Ensure caching works correctly

    - name: Install dependencies
      run: npm ci
      working-directory: my-vite-app  # <-- Set the correct folder

    - name: Run tests
      run: npm test
      working-directory: my-vite-app

    - name: Build project
      run: npm run build
      working-directory: my-vite-app
